### ISSUE TITLE
Stacktrace when running tests

### ISSUE THREAD

**Issue by koenw** [Amsterdam/iot-api#13]
When I create a clean *venv* and run the tests, they seem to succeed but I get to see a stacktrace anyway.

Steps to reproduce:
* `python -m venv /tmp/venv`
* `source /tmp/venv/bin/activate`
* `pip install -r requirements.txt -r requirements/req-test.txt`
* `docker-compose up database`
* `cd src && ./manage.py test`

Depending on the cause and your local environment, the clean *venv* might not be needed to reproduce.

Result:
```
% ./manage.py test
Using local database information
2019-11-14 11:08:36,556 - raven.contrib.django.client.DjangoClient - INFO - Raven is not configured (logging is disabled). Please see the documentation for more information.
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
....................2019-11-14 11:08:38,554 - iot.health.views - ERROR - Database connectivity failed
Traceback (most recent call last):
  File "/home/koen/projects/datapunt/iot-api/api/src/iot/health/views.py", line 13, in health
    cursor.execute('select 1')
  File "/usr/lib/python3.7/unittest/mock.py", line 965, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/usr/lib/python3.7/unittest/mock.py", line 1025, in _mock_call
    raise effect
django.db.utils.Error
2019-11-14 11:08:38,554 - iot.health.views - ERROR - Database connectivity failed
Traceback (most recent call last):
  File "/home/koen/projects/datapunt/iot-api/api/src/iot/health/views.py", line 13, in health
    cursor.execute('select 1')
  File "/usr/lib/python3.7/unittest/mock.py", line 965, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/usr/lib/python3.7/unittest/mock.py", line 1025, in _mock_call
    raise effect
django.db.utils.Error
2019-11-14 11:08:38,555 - django.request - ERROR - Internal Server Error: /status/health/
.....2019-11-14 11:08:38,622 - root - ERROR - The device with PK #99999999 could not be found in the database
.
----------------------------------------------------------------------
Ran 26 tests in 0.569s

OK
Destroying test database for alias 'default'...
```
This is not simply an issue with not being able to connect to the database at all, since if the database is not reachable it gives another error, plus it does succeed in creating the test database.

**Comment by moagstar** [comment]
This happens because the test `test_health_not_ok` is trying to verify that when a database error occurs a 500 error is returned. The test mocks the database call *so that* an error is raised, this output is therefore "expected". However I do see why it might be confusing, the solution would be to also mock the call to `log.exception` (which is nice since we can also verify that the exception is correctly logged)
